In [15]:
from tensorflow.keras.preprocessing.text import one_hot

In [16]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [17]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [18]:
## Define the vocabulary size
voc_size=10000

In [19]:
### One Hot Representation
one_hot_repr=[one_hot(word,voc_size)for word in sent]
one_hot_repr

[[9053, 4116, 2753, 5797],
 [9053, 4116, 2753, 6476],
 [9053, 5333, 2753, 6936],
 [4117, 7678, 6107, 4351, 241],
 [4117, 7678, 6107, 4351, 4391],
 [3514, 9053, 5459, 2753, 9164],
 [3334, 2522, 5078, 4351]]

In [20]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [21]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9053 4116 2753 5797]
 [   0    0    0    0 9053 4116 2753 6476]
 [   0    0    0    0 9053 5333 2753 6936]
 [   0    0    0 4117 7678 6107 4351  241]
 [   0    0    0 4117 7678 6107 4351 4391]
 [   0    0    0 3514 9053 5459 2753 9164]
 [   0    0    0    0 3334 2522 5078 4351]]


In [22]:
## feature representation
dim=10

In [23]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [26]:
# Build the model or provide input to initialize
model.build(input_shape=(None, sent_length))  # Optionally specify the batch size
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step


array([[[-0.04527341,  0.04915744, -0.01585891, -0.01427596,
          0.02434555,  0.03145634, -0.00036156, -0.03590868,
          0.02114428, -0.00850748],
        [-0.04527341,  0.04915744, -0.01585891, -0.01427596,
          0.02434555,  0.03145634, -0.00036156, -0.03590868,
          0.02114428, -0.00850748],
        [-0.04527341,  0.04915744, -0.01585891, -0.01427596,
          0.02434555,  0.03145634, -0.00036156, -0.03590868,
          0.02114428, -0.00850748],
        [-0.04527341,  0.04915744, -0.01585891, -0.01427596,
          0.02434555,  0.03145634, -0.00036156, -0.03590868,
          0.02114428, -0.00850748],
        [-0.00957173,  0.00583286, -0.0283901 ,  0.01646687,
         -0.01979038,  0.01556902,  0.02890655, -0.00659854,
         -0.0273861 , -0.00710859],
        [-0.01800298, -0.02542314, -0.00150417, -0.03745444,
          0.02981834,  0.04124758, -0.04618056, -0.01167855,
          0.00244974,  0.01798798],
        [ 0.02927235,  0.02290995, -0.04552201, -0.0

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0, 9053, 4116, 2753, 5797], dtype=int32)

In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


array([[[-0.04527341,  0.04915744, -0.01585891, -0.01427596,
          0.02434555,  0.03145634, -0.00036156, -0.03590868,
          0.02114428, -0.00850748],
        [-0.04527341,  0.04915744, -0.01585891, -0.01427596,
          0.02434555,  0.03145634, -0.00036156, -0.03590868,
          0.02114428, -0.00850748],
        [-0.04527341,  0.04915744, -0.01585891, -0.01427596,
          0.02434555,  0.03145634, -0.00036156, -0.03590868,
          0.02114428, -0.00850748],
        [-0.04527341,  0.04915744, -0.01585891, -0.01427596,
          0.02434555,  0.03145634, -0.00036156, -0.03590868,
          0.02114428, -0.00850748],
        [-0.00957173,  0.00583286, -0.0283901 ,  0.01646687,
         -0.01979038,  0.01556902,  0.02890655, -0.00659854,
         -0.0273861 , -0.00710859],
        [-0.01800298, -0.02542314, -0.00150417, -0.03745444,
          0.02981834,  0.04124758, -0.04618056, -0.01167855,
          0.00244974,  0.01798798],
        [ 0.02927235,  0.02290995, -0.04552201, -0.0