In [1]:
# Step 1: Import Libraries and Load the Model
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import load_model

In [2]:
# Load the IMDB dataset word index
word_index = imdb.get_word_index()
reverse_word_index = {value: key for key, value in word_index.items()}

In [3]:
# Load the pre-trained model with ReLU activation
model = load_model('simple_rnn_imdb.h5')
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 500, 128)       │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,313,027 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [4]:
model.get_weights()

[array([[-0.04351277,  0.09131225,  0.1152138 , ...,  0.09961382,
          0.01747077, -0.05438497],
        [ 0.02658155, -0.02538218,  0.0516704 , ..., -0.00426466,
         -0.06483845, -0.00617821],
        [-0.05414072, -0.04026032,  0.02656511, ..., -0.01050089,
          0.02489396, -0.00328179],
        ...,
        [ 0.09782659, -0.0375167 ,  0.05205624, ...,  0.11258015,
          0.11144682, -0.03136888],
        [-0.010132  ,  0.0714925 , -0.10440867, ..., -0.02333666,
         -0.02588255,  0.00559546],
        [ 0.0006213 , -0.09204315,  0.01638029, ...,  0.02656934,
          0.03670881, -0.07283378]], dtype=float32),
 array([[ 0.10901588,  0.01708283,  0.00809171, ...,  0.09043752,
          0.04487565, -0.00992778],
        [ 0.01059398,  0.03437495, -0.00076253, ..., -0.0422807 ,
         -0.09492573,  0.13656662],
        [ 0.0689438 , -0.10217457, -0.00853403, ..., -0.03308404,
         -0.10653935, -0.16786908],
        ...,
        [-0.03149423, -0.0245521 , -0.0

In [5]:
# Step 2: Helper Functions
# Function to decode reviews
def decode_review(encoded_review):
    return ' '.join([reverse_word_index.get(i - 3, '?') for i in encoded_review])

# Function to preprocess user input
def preprocess_text(text):
    words = text.lower().split()
    encoded_review = [word_index.get(word, 2) + 3 for word in words]
    padded_review = sequence.pad_sequences([encoded_review], maxlen=500)
    return padded_review

In [6]:
### Prediction  function

def predict_sentiment(review):
    preprocessed_input=preprocess_text(review)

    prediction=model.predict(preprocessed_input)

    sentiment = 'Positive' if prediction[0][0] > 0.5 else 'Negative'
    
    return sentiment, prediction[0][0]

In [7]:
# Step 4: User Input and Prediction
# Example review for prediction
example_review = "This movie was fantastic! The acting was great and the plot was thrilling."

sentiment,score=predict_sentiment(example_review)

print(f'Review: {example_review}')
print(f'Sentiment: {sentiment}')
print(f'Prediction Score: {score}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step
Review: This movie was fantastic! The acting was great and the plot was thrilling.
Sentiment: Positive
Prediction Score: 0.5597849488258362


In [8]:
preprocessed_input=preprocess_text("This movie was fantastic! The acting was great and the plot was thrilling.")
prediction=model.predict(preprocessed_input)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


array([[0.55978495]], dtype=float32)

In [9]:
prediction[0]

array([0.55978495], dtype=float32)

In [10]:
len(prediction[0])

1

In [11]:
prediction[0][0]

0.55978495